### ISSUE TITLE
Running the Node with Snapshot: Impossible to download a Snapshot:

### ISSUE THREAD

**Issue by alfaori1977** [bnb-chain/op-geth#29]
#### System information

**Network**: `testnet`

**op-node version**: op-node version v0.0.0-a958e47e-1692755212
**op-geth version**:
Version: 0.1.0-unstable
Git Commit: https://github.com/bnb-chain/op-geth/commit/0b3e557324a7717b598ca877f7350d346e9c1ada
Git Commit Date: 20230808
Upstream Version: 1.11.5-stable
Architecture: amd64
Go Version: go1.20.5
Operating System: linux
GOPATH=
GOROOT=
**OS & Version**: "Ubuntu 20.04.5 LTS"

#### Expected behaviour
Snapshot should be downloaded

#### Actual behaviour
`ERROR: Permision Denied/403 Forbidden`, both at the explorer (Chrome, Firefox, Brave) and also from command line

#### Steps to reproduce the behaviour
Just follow the guide at: https://docs.bnbchain.org/opbnb-docs/docs/tutorials/running-node-with-snapshot#testnet
```
**wget  https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20231012.tar.gz**

--2023-11-06 08:31:56--  https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20231012.tar.gz
Resolving tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com (tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com)... 52.219.8.39, 52.219.199.166, 3.5.157.161, ...
Connecting to tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com (tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com)|52.219.8.39|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-06 08:31:57 ERROR 403: Forbidden.
```

**Comment by STdevK** [comment]
Do kindly refer to the latest snapshot url here.
https://github.com/bnb-chain/opbnb-snapshot

As of 7th Nov, the latest available snapshot url is https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20231102.tar.gz
